//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Защитник
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class StrazhnikEntities : DbContext
    {
        private static StrazhnikEntities _context;
        public StrazhnikEntities()
            : base("name=StrazhnikEntities")
        {
        }
        public static StrazhnikEntities GetContext()
        {
            if (_context == null)
            {
                _context = new StrazhnikEntities();
            }
            return _context;
        }
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ГруппаПользователя> ГруппаПользователя { get; set; }
        public virtual DbSet<Заказ> Заказ { get; set; }
        public virtual DbSet<МандатДоступа> МандатДоступа { get; set; }
        public virtual DbSet<Пользователь> Пользователь { get; set; }
        public virtual DbSet<Предприятие> Предприятие { get; set; }
        public virtual DbSet<Продукт> Продукт { get; set; }
        public virtual DbSet<Событие> Событие { get; set; }
        public virtual DbSet<УровеньДоступа> УровеньДоступа { get; set; }
    }
}
