//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Защитник
{
    using System;
    using System.Collections.Generic;
    
    public partial class УровеньДоступа
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public УровеньДоступа()
        {
            this.МандатДоступа = new HashSet<МандатДоступа>();
        }
    
        public int КодУровня { get; set; }
        public string НазваниеУровня { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<МандатДоступа> МандатДоступа { get; set; }
    }
}
